        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      ISR_Reset ; Reset               ; Int 08h (IRQ 0)
        dd      ISR_Tick ; Tick                ; Int 09h (IRQ 1)
        dd      ISR_Keyboard ; Keyboard            ; Int 0Ah (IRQ 2)
        dd      0 ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      0 ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      0 ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      0 ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      0 ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      0                       ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)
	
	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84

; Generated by c86 (BYU-NASM) 5.1 (beta) from lab4b_app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab4b_app_2:
	DB	"Starting kernel...",0xA,0
L_lab4b_app_1:
	DB	"Creating task...",0xA,0
	ALIGN	2
main:
	; >>>>> Line:	17
	; >>>>> { 
	jmp	L_lab4b_app_3
L_lab4b_app_4:
	; >>>>> Line:	18
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	20
	; >>>>> printString("Creating task...\n"); 
	mov	ax, L_lab4b_app_1
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	21
	; >>>>> YKNewTask(Task, (void *) &TaskStack[256], 0); 
	xor	al, al
	push	ax
	mov	ax, (TaskStack+512)
	push	ax
	mov	ax, Task
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	23
	; >>>>> printString("Starting kernel...\n"); 
	mov	ax, L_lab4b_app_2
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	24
	; >>>>> YKRun(); 
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab4b_app_3:
	push	bp
	mov	bp, sp
	jmp	L_lab4b_app_4
L_lab4b_app_9:
	DB	" context switches! YKIdleCount is ",0
L_lab4b_app_8:
	DB	"Task running after ",0
L_lab4b_app_7:
	DB	"Delaying task...",0xA,0
L_lab4b_app_6:
	DB	"Task started.",0xA,0
	ALIGN	2
Task:
	; >>>>> Line:	28
	; >>>>> { 
	jmp	L_lab4b_app_10
L_lab4b_app_11:
	; >>>>> Line:	32
	; >>>>> printString("Task started.\n"); 
	mov	ax, L_lab4b_app_6
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	33
	; >>>>> while (1) 
	jmp	L_lab4b_app_13
L_lab4b_app_12:
	; >>>>> Line:	35
	; >>>>> printString("Delaying task...\n"); 
	mov	ax, L_lab4b_app_7
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	37
	; >>>>> YKDelayTask(2); 
	mov	ax, 2
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	39
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	40
	; >>>>> numCtxSwitches = YKCtxSwCount; 
	mov	ax, word [YKCtxSwCount]
	mov	word [bp-4], ax
	; >>>>> Line:	41
	; >>>>> idleCount = YKIdleCount; 
	mov	ax, word [YKIdleCount]
	mov	word [bp-2], ax
	; >>>>> Line:	42
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	43
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	45
	; >>>>> printString("Task running after "); 
	mov	ax, L_lab4b_app_8
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	46
	; >>>>> printUInt(numCtxSwitches); 
	push	word [bp-4]
	call	printUInt
	add	sp, 2
	; >>>>> Line:	47
	; >>>>> printString(" context switches! YKIdleCount is "); 
	mov	ax, L_lab4b_app_9
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	48
	; >>>>> printUInt(idleCount); 
	push	word [bp-2]
	call	printUInt
	add	sp, 2
	; >>>>> Line:	49
	; >>>>> printString(".\n"); 
	mov	ax, (L_lab4b_app_1+15)
	push	ax
	call	printString
	add	sp, 2
L_lab4b_app_13:
	jmp	L_lab4b_app_12
L_lab4b_app_14:
	mov	sp, bp
	pop	bp
	ret
L_lab4b_app_10:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_lab4b_app_11
	ALIGN	2
TaskStack:
	TIMES	512 db 0

enable_interrupts:
	sti	
	ret

disable_interrupts:
	cli
	ret

YKSecond:
	push bp
	mov bp, sp
	pushf
	push cs
	push word [ipLabelFirst]

	push ax
	push bx
	push cx
	push dx
	push si
	push di
	push bp
	push es
	push ds

	mov si, word[old_task]
	mov [si], sp	
	mov si, word[running_task]
	mov sp, [si]
		
	iret

	ipLabelFirst: DW Label2

Label2:
	mov sp, bp
	pop bp
	ret

YKFirst:
	;push bp
	;mov bp, sp

	mov si, word[running_task]
	mov sp, [si]
	mov ax, 0x200
	add si, 2
	mov si, [si]
	
	push ax
	push cs
	push si
	iret			

YKISR:
	mov si, word[old_task]
	mov [si], sp
	mov si, word[running_task]
	mov sp, [si]	;move the new sp to the sp register			
	pop ds
	pop es
	pop bp
	pop di
	pop si
	pop dx
	pop cx
	pop bx
	pop ax
	iret		; this assumes that the top of the stack is ip, cs, flags. iret atomically pops those three and returns instruction control to the new ip
	
YKDispHandler:
	
	push bp
	mov bp, sp

	pushf
	push cs
	push word [ipLabel]	

	push ax
	push bx
	push cx
	push dx
	push si
	push di
	push bp
	push es
	push ds
		
;save old sp and get new sp
	mov si, word[old_task]
	mov [si], sp
	mov si, word[running_task]
	mov sp, [si]

	pop ds
	pop es
	pop bp
	pop di
	pop si
	pop dx
	pop cx
	pop bx
	pop ax
	iret

	ipLabel: DW Label1

Label1:
	mov sp, bp
	pop bp
	ret









;GetIP:
;	push bp
;	mov bp, sp
	
;	mov ax, word[bp+2]
	
;	mov sp, bp
;	pop bp
;	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
next_available_tcb:
	DW	0
YK_running:
	DW	0
	ALIGN	2
YKInitialize:
	; >>>>> Line:	33
	; >>>>> { 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	35
	; >>>>> YKNewTask(YKIdleTask, (void *)&IdleTskStk[256], 100); 
	mov	al, 100
	push	ax
	mov	ax, (IdleTskStk+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	36
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	37
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	38
	; >>>>> YKTickNum = 0; 
	mov	word [YKTickNum], 0
	; >>>>> Line:	39
	; >>>>> YK_Depth = 0; 
	mov	word [YK_Depth], 0
	; >>>>> Line:	40
	; >>>>> FirstTime = 1; 
	mov	word [FirstTime], 1
	; >>>>> Line:	41
	; >>>>> depthMoreOne = 0; 
	mov	word [depthMoreOne], 0
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	jmp	L_yakc_2
	ALIGN	2
YKEnterMutex:
	; >>>>> Line:	50
	; >>>>> void YKEnterMutex(void) { 
	jmp	L_yakc_4
L_yakc_5:
	; >>>>> Line:	51
	; >>>>> disable_interrupts(); 
	call	disable_interrupts
	mov	sp, bp
	pop	bp
	ret
L_yakc_4:
	push	bp
	mov	bp, sp
	jmp	L_yakc_5
	ALIGN	2
YKExitMutex:
	; >>>>> Line:	54
	; >>>>> void YKExitMutex(void) { 
	jmp	L_yakc_7
L_yakc_8:
	; >>>>> Line:	55
	; >>>>> enable_interrupts(); 
	call	enable_interrupts
	mov	sp, bp
	pop	bp
	ret
L_yakc_7:
	push	bp
	mov	bp, sp
	jmp	L_yakc_8
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	59
	; >>>>> { 
	jmp	L_yakc_10
L_yakc_11:
	; >>>>> Line:	60
	; >>>>> while (1) 
	jmp	L_yakc_13
L_yakc_12:
	; >>>>> Line:	62
	; >>>>> ++YKIdleCount; 
	inc	word [YKIdleCount]
	; >>>>> Line:	63
	; >>>>> --YKIdleCount; 
	dec	word [YKIdleCount]
	; >>>>> Line:	64
	; >>>>> ++YKIdleCount; 
	inc	word [YKIdleCount]
L_yakc_13:
	jmp	L_yakc_12
L_yakc_14:
	mov	sp, bp
	pop	bp
	ret
L_yakc_10:
	push	bp
	mov	bp, sp
	jmp	L_yakc_11
	ALIGN	2
YKNewTask:
	; >>>>> Line:	70
	; >>>>> { 
	jmp	L_yakc_16
L_yakc_17:
	; >>>>> Line:	73
	; >>>>> tcb_array[index].delay_counter = 0; 
	mov	ax, word [next_available_tcb]
	mov	word [bp-2], ax
	mov	ax, word [YKList]
	mov	word [bp-4], ax
	; >>>>> Line:	73
	; >>>>> tcb_array[index].delay_counter = 0; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	74
	; >>>>> tcb_array[index].id = next_available_tcb; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 4
	mov	ax, word [next_available_tcb]
	mov	word [si], ax
	; >>>>> Line:	75
	; >>>>> tcb_array[index].priority = priority; 
	mov	al, byte [bp+8]
	xor	ah, ah
	push	ax
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	mov	dx, ax
	add	dx, tcb_array
	mov	si, dx
	add	si, 6
	pop	ax
	mov	word [si], ax
	; >>>>> Line:	76
	; >>>>> tcb_array[index].task = (void*)task; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 18
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	77
	; >>>>> tcb_array[index].pInst = (void*)(task); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 2
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	78
	; >>>>> tcb_array[index].pStck = (int*)(taskStack); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	mov	si, ax
	add	si, tcb_array
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	79
	; >>>>> tcb_array[index].state = READY; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 8
	mov	word [si], 1
	; >>>>> Line:	80
	; >>>>> tcb_array[index].firstTime = 1; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 20
	mov	word [si], 1
	; >>>>> Line:	81
	; >>>>> next_available_tcb++; 
	inc	word [next_available_tcb]
	; >>>>> Line:	83
	; >>>>> if (index == 0) YKList = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_18
	; >>>>> Line:	83
	; >>>>> if (index == 0) YKList = &(tcb_array[index]); 
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	word [YKList], ax
L_yakc_18:
	; >>>>> Line:	85
	; >>>>> while (tempHead != 0) { 
	jmp	L_yakc_20
L_yakc_19:
	; >>>>> Line:	86
	; >>>>> t 
	mov	si, word [bp-4]
	add	si, 6
	mov	al, byte [bp+8]
	xor	ah, ah
	cmp	ax, word [si]
	jge	L_yakc_22
	; >>>>> Line:	88
	; >>>>> if (YKList == tempHead) { 
	mov	ax, word [bp-4]
	cmp	ax, word [YKList]
	jne	L_yakc_23
	; >>>>> Line:	89
	; >>>>> YKList->prev = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, word [YKList]
	add	si, 14
	mov	word [si], ax
	; >>>>> Line:	90
	; >>>>> tcb_array[index].next = YKList; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 16
	mov	ax, word [YKList]
	mov	word [si], ax
	; >>>>> Line:	91
	; >>>>> YKList = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	word [YKList], ax
	jmp	L_yakc_24
L_yakc_23:
	; >>>>> Line:	94
	; >>>>> tcb_array[index].next = tempHead; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 16
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	95
	; >>>>> tcb_array[index].prev = tempHead->prev; 
	mov	si, word [bp-4]
	add	si, 14
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	di, ax
	add	di, 14
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	96
	; >>>>> tempHead->prev->next = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, word [bp-4]
	add	si, 14
	mov	si, word [si]
	add	si, 16
	mov	word [si], ax
	; >>>>> Line:	97
	; >>>>> tempHead->prev = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, word [bp-4]
	add	si, 14
	mov	word [si], ax
L_yakc_24:
	; >>>>> Line:	99
	; >>>>> tempHead = 0; 
	mov	word [bp-4], 0
	jmp	L_yakc_25
L_yakc_22:
	; >>>>> Line:	103
	; >>>>> tempHead = tempHead->next; 
	mov	si, word [bp-4]
	add	si, 16
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakc_25:
L_yakc_20:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_19
L_yakc_21:
	; >>>>> Line:	106
	; >>>>> if (YK_running) { 
	mov	ax, word [YK_running]
	test	ax, ax
	je	L_yakc_26
	; >>>>> Line:	107
	; >>>>> YKScheduler(2); 
	mov	ax, 2
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_26:
	mov	sp, bp
	pop	bp
	ret
L_yakc_16:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_17
	ALIGN	2
YKRun:
	; >>>>> Line:	114
	; >>>>> { 
	jmp	L_yakc_28
L_yakc_29:
	; >>>>> Line:	115
	; >>>>> if (YKList 
	mov	ax, tcb_array
	cmp	ax, word [YKList]
	je	L_yakc_30
	; >>>>> Line:	116
	; >>>>> YK_running = 1; 
	mov	word [YK_running], 1
	; >>>>> Line:	117
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_30:
	mov	sp, bp
	pop	bp
	ret
L_yakc_28:
	push	bp
	mov	bp, sp
	jmp	L_yakc_29
	ALIGN	2
YKScheduler:
	; >>>>> Line:	126
	; >>>>> { 
	jmp	L_yakc_32
L_yakc_33:
	; >>>>> Line:	129
	; >>>>> YKEnterMutex(); 
	mov	ax, word [YKList]
	mov	word [bp-2], ax
	; >>>>> Line:	129
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	130
	; >>>>> while (currentTCB != 0) { 
	jmp	L_yakc_35
L_yakc_34:
	; >>>>> Line:	131
	; >>>>> if (currentTCB->state == RUNNING) { 
	mov	si, word [bp-2]
	add	si, 8
	cmp	word [si], 2
	jne	L_yakc_37
	; >>>>> Line:	132
	; >>>>> break; 
	jmp	L_yakc_36
	jmp	L_yakc_38
L_yakc_37:
	; >>>>> Line:	134
	; >>>>> else if (currentTCB->state == READY) { 
	mov	si, word [bp-2]
	add	si, 8
	cmp	word [si], 1
	jne	L_yakc_39
	; >>>>> Line:	135
	; >>>>> ++YKCtxSwCount; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	136
	; >>>>> YKDispatcher(currentTCB, dispatcher_type); 
	push	word [bp+4]
	push	word [bp-2]
	call	YKDispatcher
	add	sp, 4
	; >>>>> Line:	137
	; >>>>> break; 
	jmp	L_yakc_36
L_yakc_39:
L_yakc_38:
	; >>>>> Line:	139
	; >>>>> currentTCB = currentTCB->next; 
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_35:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_34
L_yakc_36:
	; >>>>> Line:	141
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_32:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_33
L_yakc_41:
	DB	"block dispatch",0xA,0
	ALIGN	2
YKDispatcher:
	; >>>>> Line:	159
	; >>>>> { 
	jmp	L_yakc_42
L_yakc_43:
	; >>>>> Line:	163
	; >>>>> old_task = running_task; 
	mov	word [bp-2], 0
	mov	si, word [bp+4]
	add	si, 20
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	163
	; >>>>> old_task = running_task; 
	mov	ax, word [running_task]
	mov	word [old_task], ax
	; >>>>> Line:	165
	; >>>>> if(FirstTime) { 
	mov	ax, word [FirstTime]
	test	ax, ax
	je	L_yakc_44
	; >>>>> Line:	166
	; >>>>> task->firstTime = 0; 
	mov	si, word [bp+4]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	167
	; >>>>> FirstTime = 0; 
	mov	word [FirstTime], 0
	; >>>>> Line:	169
	; >>>>> running_task = task; 
	mov	ax, word [bp+4]
	mov	word [running_task], ax
	jmp	L_yakc_45
L_yakc_44:
	; >>>>> Line:	172
	; >>>>> else if (running_task->state == BLOCKED) { 
	mov	si, word [running_task]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_46
	; >>>>> Line:	173
	; >>>>> running_task = task; 
	mov	ax, word [bp+4]
	mov	word [running_task], ax
	; >>>>> Line:	174
	; >>>>> if (!(task->firstTime)) { 
	mov	si, word [bp+4]
	add	si, 20
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_47
	; >>>>> Line:	175
	; >>>>> task->firstTime = 0; 
	mov	si, word [bp+4]
	add	si, 20
	mov	word [si], 0
	jmp	L_yakc_48
L_yakc_47:
	; >>>>> Line:	181
	; >>>>> task->firstTime = 0; 
	mov	si, word [bp+4]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	182
	; >>>>> task->state = RUNNING; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 2
L_yakc_48:
	jmp	L_yakc_49
L_yakc_46:
	; >>>>> Line:	188
	; >>>>> task->firstTime = 0; 
	mov	si, word [bp+4]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	190
	; >>>>> old_task->state = READY; 
	mov	si, word [old_task]
	add	si, 8
	mov	word [si], 1
	; >>>>> Line:	191
	; >>>>> task->state = RUNNING; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 2
	; >>>>> Line:	192
	; >>>>> e 
	mov	ax, word [bp+4]
	mov	word [running_task], ax
L_yakc_49:
L_yakc_45:
	; >>>>> Line:	198
	; >>>>> if (dispatcher_type == 2) { 
	cmp	word [bp+6], 2
	jne	L_yakc_50
	; >>>>> Line:	199
	; >>>>> printString("block dispatch\n"); 
	mov	ax, L_yakc_41
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	200
	; >>>>> if(enable){ 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_51
	; >>>>> Line:	201
	; >>>>> YKSecond(); 
	call	YKSecond
	jmp	L_yakc_52
L_yakc_51:
	; >>>>> Line:	204
	; >>>>> YKDispHandler(); 
	call	YKDispHandler
L_yakc_52:
	jmp	L_yakc_53
L_yakc_50:
	; >>>>> Line:	207
	; >>>>> else if (dispatcher_type == 0) { 
	mov	ax, word [bp+6]
	test	ax, ax
	jne	L_yakc_54
	; >>>>> Line:	208
	; >>>>> YKFirst(); 
	call	YKFirst
	jmp	L_yakc_55
L_yakc_54:
	; >>>>> Line:	211
	; >>>>> YKISR(); 
	call	YKISR
L_yakc_55:
L_yakc_53:
	mov	sp, bp
	pop	bp
	ret
L_yakc_42:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_43
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	219
	; >>>>> { 
	jmp	L_yakc_57
L_yakc_58:
	; >>>>> Line:	221
	; >>>>> if (count == 0) return; 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_59
	; >>>>> Line:	221
	; >>>>> if (count == 0) return; 
	jmp	L_yakc_60
L_yakc_59:
	; >>>>> Line:	222
	; >>>>> running_task->delay_counter = count; 
	mov	si, word [running_task]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	223
	; >>>>> running_task->state = BLOCKED; 
	mov	si, word [running_task]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	226
	; >>>>> YKScheduler(2); 
	mov	ax, 2
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_60:
	mov	sp, bp
	pop	bp
	ret
L_yakc_57:
	push	bp
	mov	bp, sp
	jmp	L_yakc_58
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	233
	; >>>>> { 
	jmp	L_yakc_62
L_yakc_63:
	; >>>>> Line:	234
	; >>>>> ++YK_Depth; 
	inc	word [YK_Depth]
	mov	sp, bp
	pop	bp
	ret
L_yakc_62:
	push	bp
	mov	bp, sp
	jmp	L_yakc_63
	ALIGN	2
YKExitISR:
	; >>>>> Line:	239
	; >>>>> { 
	jmp	L_yakc_65
L_yakc_66:
	; >>>>> Line:	240
	; >>>>> --YK_Depth; 
	dec	word [YK_Depth]
	; >>>>> Line:	241
	; >>>>> if (YK_Depth == 0){ 
	mov	ax, word [YK_Depth]
	test	ax, ax
	jne	L_yakc_67
	; >>>>> Line:	242
	; >>>>> depthMoreOne = 0; 
	mov	word [depthMoreOne], 0
	; >>>>> Line:	243
	; >>>>> YKSche 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_67:
	mov	sp, bp
	pop	bp
	ret
L_yakc_65:
	push	bp
	mov	bp, sp
	jmp	L_yakc_66
L_yakc_69:
	DB	"Set to ready",0xA,0
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	250
	; >>>>> { 
	jmp	L_yakc_70
L_yakc_71:
	; >>>>> Line:	252
	; >>>>> ++YKTickNum; 
	mov	ax, word [YKList]
	mov	word [bp-2], ax
	; >>>>> Line:	252
	; >>>>> ++YKTickNum; 
	inc	word [YKTickNum]
	; >>>>> Line:	253
	; >>>>> while (currentTCB != 0) { 
	jmp	L_yakc_73
L_yakc_72:
	; >>>>> Line:	254
	; >>>>> if (currentTCB->task == YKIdleTask) return; 
	mov	si, word [bp-2]
	add	si, 18
	mov	ax, YKIdleTask
	cmp	ax, word [si]
	jne	L_yakc_75
	; >>>>> Line:	254
	; >>>>> if (currentTCB->task == YKIdleTask) return; 
	jmp	L_yakc_76
L_yakc_75:
	; >>>>> Line:	256
	; >>>>> if (currentTCB->delay_counter != 0) { 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_77
	; >>>>> Line:	257
	; >>>>> --(currentTCB->delay_counter); 
	mov	si, word [bp-2]
	add	si, 12
	dec	word [si]
	; >>>>> Line:	258
	; >>>>> if (currentTCB->delay_counter == 0) { 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_78
	; >>>>> Line:	259
	; >>>>> currentTCB->state = READY; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 1
	; >>>>> Line:	260
	; >>>>> printString("Set to ready\n"); 
	mov	ax, L_yakc_69
	push	ax
	call	printString
	add	sp, 2
L_yakc_78:
L_yakc_77:
	; >>>>> Line:	263
	; >>>>> currentTCB = currentTCB->next; 
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_73:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_72
L_yakc_74:
L_yakc_76:
	mov	sp, bp
	pop	bp
	ret
L_yakc_70:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_71
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
YK_Depth:
	TIMES	2 db 0
FirstTime:
	TIMES	2 db 0
tcb_array:
	TIMES	44 db 0
YKList:
	TIMES	2 db 0
running_task:
	TIMES	2 db 0
old_task:
	TIMES	2 db 0
IdleTskStk:
	TIMES	512 db 0
depthMoreOne:
	TIMES	2 db 0
ISR_Reset:
	push ax
	push bx
	push cx
	push dx
	push si
	push di
	push bp
	push es
	push ds

	call YKEnterISR
	sti
	
	call vReset

	cli
	call signalEOI
	call YKExitISR
	pop ds
	pop es
	pop bp
	pop di
	pop si
	pop dx
	pop cx
	pop bx
	pop ax
	iret
ISR_Tick:
	
	push ax
	push bx
	push cx
	push dx
	push si
	push di
	push bp
	push es
	push ds
	call YKEnterISR
	sti
	
	call vTick
	call YKTickHandler

	cli
	call signalEOI
	call YKExitISR
	
	pop ds
	pop es
	pop bp
	pop di
	pop si
	pop dx
	pop cx
	pop bx
	pop ax
	iret

ISR_Keyboard:


	push ax
	push bx
	push cx
	push dx
	push si
	push di
	push bp
	push es
	push ds
	call YKEnterISR
	sti
	
	call vKeyboard

	cli
	call signalEOI
	call YKExitISR
	pop ds
	pop es
	pop bp
	pop di
	pop si
	pop dx
	pop cx
	pop bx
	pop ax
	iret; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
L_myinth_1:
	DW	0
	ALIGN	2
vReset:
	; >>>>> Line:	6
	; >>>>> { 
	jmp	L_myinth_2
L_myinth_3:
	; >>>>> Line:	7
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_2:
	push	bp
	mov	bp, sp
	jmp	L_myinth_3
L_myinth_6:
	DB	0xA,0
L_myinth_5:
	DB	0xA,"TICK ",0
	ALIGN	2
vTick:
	; >>>>> Line:	11
	; >>>>> { 
	jmp	L_myinth_7
L_myinth_8:
	; >>>>> Line:	13
	; >>>>> printString("\nTICK "); 
	mov	ax, L_myinth_5
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	14
	; >>>>> printUInt(++tick); 
	mov	ax, word [L_myinth_1]
	inc	ax
	mov	word [L_myinth_1], ax
	push	ax
	call	printUInt
	add	sp, 2
	; >>>>> Line:	15
	; >>>>> printString("\n"); 
	mov	ax, L_myinth_6
	push	ax
	call	printString
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_7:
	push	bp
	mov	bp, sp
	jmp	L_myinth_8
L_myinth_13:
	DB	") IGNORED",0xA,0
L_myinth_12:
	DB	0xA,"KEYPRESS (",0
L_myinth_11:
	DB	0xA,"DELAY COMPLETE",0xA,0
L_myinth_10:
	DB	0xA,"DELAY KEY PRESSED",0xA,0
	ALIGN	2
vKeyboard:
	; >>>>> Line:	19
	; >>>>> { 
	jmp	L_myinth_14
L_myinth_15:
	; >>>>> Line:	21
	; >>>>> if((char)KeyBuffer == 'd'){ 
	cmp	byte [KeyBuffer], 100
	jne	L_myinth_16
	; >>>>> Line:	22
	; >>>>> printString("\nDELAY KEY PRESSED\n"); 
	mov	ax, L_myinth_10
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	23
	; >>>>> loop_tick = 0; 
	mov	word [bp-2], 0
	; >>>>> Line:	24
	; >>>>> while(loop_tick < 5000){ 
	jmp	L_myinth_18
L_myinth_17:
	; >>>>> Line:	25
	; >>>>> ++loop_tick; 
	inc	word [bp-2]
L_myinth_18:
	cmp	word [bp-2], 5000
	jl	L_myinth_17
L_myinth_19:
	; >>>>> Line:	28
	; >>>>> printString("\nDELAY COMPLETE\n"); 
	mov	ax, L_myinth_11
	push	ax
	call	printString
	add	sp, 2
	jmp	L_myinth_20
L_myinth_16:
	; >>>>> Line:	31
	; >>>>> printString("\nKEYPRESS ("); 
	mov	ax, L_myinth_12
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	32
	; >>>>> printChar((char)KeyBuffer); 
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	33
	; >>>>> printString(") IGNORED\n") 
	mov	ax, L_myinth_13
	push	ax
	call	printString
	add	sp, 2
L_myinth_20:
	mov	sp, bp
	pop	bp
	ret
L_myinth_14:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_15
