; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
next_available_tcb:
	DW	0
YK_running:
	DW	0
	ALIGN	2
YKInitialize:
	; >>>>> Line:	33
	; >>>>> { 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	35
	; >>>>> YKNewTask(YKIdleTask, (void *)&IdleTskStk[256], 100); 
	mov	al, 100
	push	ax
	mov	ax, (IdleTskStk+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	36
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	37
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	38
	; >>>>> YKTickNum = 0; 
	mov	word [YKTickNum], 0
	; >>>>> Line:	39
	; >>>>> YK_Depth = 0; 
	mov	word [YK_Depth], 0
	; >>>>> Line:	40
	; >>>>> FirstTime = 1; 
	mov	word [FirstTime], 1
	; >>>>> Line:	41
	; >>>>> depthMoreOne = 0; 
	mov	word [depthMoreOne], 0
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	jmp	L_yakc_2
	ALIGN	2
YKEnterMutex:
	; >>>>> Line:	50
	; >>>>> void YKEnterMutex(void) { 
	jmp	L_yakc_4
L_yakc_5:
	; >>>>> Line:	51
	; >>>>> disable_interrupts(); 
	call	disable_interrupts
	mov	sp, bp
	pop	bp
	ret
L_yakc_4:
	push	bp
	mov	bp, sp
	jmp	L_yakc_5
	ALIGN	2
YKExitMutex:
	; >>>>> Line:	54
	; >>>>> void YKExitMutex(void) { 
	jmp	L_yakc_7
L_yakc_8:
	; >>>>> Line:	55
	; >>>>> enable_interrupts(); 
	call	enable_interrupts
	mov	sp, bp
	pop	bp
	ret
L_yakc_7:
	push	bp
	mov	bp, sp
	jmp	L_yakc_8
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	59
	; >>>>> { 
	jmp	L_yakc_10
L_yakc_11:
	; >>>>> Line:	60
	; >>>>> while (1) 
	jmp	L_yakc_13
L_yakc_12:
	; >>>>> Line:	62
	; >>>>> ++YKIdleCount; 
	inc	word [YKIdleCount]
	; >>>>> Line:	63
	; >>>>> --YKIdleCount; 
	dec	word [YKIdleCount]
	; >>>>> Line:	64
	; >>>>> ++YKIdleCount; 
	inc	word [YKIdleCount]
L_yakc_13:
	jmp	L_yakc_12
L_yakc_14:
	mov	sp, bp
	pop	bp
	ret
L_yakc_10:
	push	bp
	mov	bp, sp
	jmp	L_yakc_11
	ALIGN	2
YKNewTask:
	; >>>>> Line:	70
	; >>>>> { 
	jmp	L_yakc_16
L_yakc_17:
	; >>>>> Line:	73
	; >>>>> tcb_array[index].delay_counter = 0; 
	mov	ax, word [next_available_tcb]
	mov	word [bp-2], ax
	mov	ax, word [YKList]
	mov	word [bp-4], ax
	; >>>>> Line:	73
	; >>>>> tcb_array[index].delay_counter = 0; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	74
	; >>>>> tcb_array[index].id = next_available_tcb; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 4
	mov	ax, word [next_available_tcb]
	mov	word [si], ax
	; >>>>> Line:	75
	; >>>>> tcb_array[index].priority = priority; 
	mov	al, byte [bp+8]
	xor	ah, ah
	push	ax
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	mov	dx, ax
	add	dx, tcb_array
	mov	si, dx
	add	si, 6
	pop	ax
	mov	word [si], ax
	; >>>>> Line:	76
	; >>>>> tcb_array[index].task = (void*)task; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 18
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	77
	; >>>>> tcb_array[index].pInst = (void*)(task); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 2
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	78
	; >>>>> tcb_array[index].pStck = (int*)(taskStack); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	mov	si, ax
	add	si, tcb_array
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	79
	; >>>>> tcb_array[index].state = READY; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 8
	mov	word [si], 1
	; >>>>> Line:	80
	; >>>>> tcb_array[index].firstTime = 1; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 20
	mov	word [si], 1
	; >>>>> Line:	81
	; >>>>> next_available_tcb++; 
	inc	word [next_available_tcb]
	; >>>>> Line:	83
	; >>>>> if (index == 0) YKList = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_18
	; >>>>> Line:	83
	; >>>>> if (index == 0) YKList = &(tcb_array[index]); 
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	word [YKList], ax
L_yakc_18:
	; >>>>> Line:	85
	; >>>>> while (tempHead != 0) { 
	jmp	L_yakc_20
L_yakc_19:
	; >>>>> Line:	86
	; >>>>> t 
	mov	si, word [bp-4]
	add	si, 6
	mov	al, byte [bp+8]
	xor	ah, ah
	cmp	ax, word [si]
	jge	L_yakc_22
	; >>>>> Line:	88
	; >>>>> if (YKList == tempHead) { 
	mov	ax, word [bp-4]
	cmp	ax, word [YKList]
	jne	L_yakc_23
	; >>>>> Line:	89
	; >>>>> YKList->prev = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, word [YKList]
	add	si, 14
	mov	word [si], ax
	; >>>>> Line:	90
	; >>>>> tcb_array[index].next = YKList; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 16
	mov	ax, word [YKList]
	mov	word [si], ax
	; >>>>> Line:	91
	; >>>>> YKList = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	word [YKList], ax
	jmp	L_yakc_24
L_yakc_23:
	; >>>>> Line:	94
	; >>>>> tcb_array[index].next = tempHead; 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, ax
	add	si, 16
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	95
	; >>>>> tcb_array[index].prev = tempHead->prev; 
	mov	si, word [bp-4]
	add	si, 14
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	di, ax
	add	di, 14
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	96
	; >>>>> tempHead->prev->next = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, word [bp-4]
	add	si, 14
	mov	si, word [si]
	add	si, 16
	mov	word [si], ax
	; >>>>> Line:	97
	; >>>>> tempHead->prev = &(tcb_array[index]); 
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	add	ax, tcb_array
	mov	si, word [bp-4]
	add	si, 14
	mov	word [si], ax
L_yakc_24:
	; >>>>> Line:	99
	; >>>>> tempHead = 0; 
	mov	word [bp-4], 0
	jmp	L_yakc_25
L_yakc_22:
	; >>>>> Line:	103
	; >>>>> tempHead = tempHead->next; 
	mov	si, word [bp-4]
	add	si, 16
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakc_25:
L_yakc_20:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_19
L_yakc_21:
	; >>>>> Line:	106
	; >>>>> if (YK_running) { 
	mov	ax, word [YK_running]
	test	ax, ax
	je	L_yakc_26
	; >>>>> Line:	107
	; >>>>> YKScheduler(2); 
	mov	ax, 2
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_26:
	mov	sp, bp
	pop	bp
	ret
L_yakc_16:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_17
	ALIGN	2
YKRun:
	; >>>>> Line:	114
	; >>>>> { 
	jmp	L_yakc_28
L_yakc_29:
	; >>>>> Line:	115
	; >>>>> if (YKList 
	mov	ax, tcb_array
	cmp	ax, word [YKList]
	je	L_yakc_30
	; >>>>> Line:	116
	; >>>>> YK_running = 1; 
	mov	word [YK_running], 1
	; >>>>> Line:	117
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_30:
	mov	sp, bp
	pop	bp
	ret
L_yakc_28:
	push	bp
	mov	bp, sp
	jmp	L_yakc_29
	ALIGN	2
YKScheduler:
	; >>>>> Line:	126
	; >>>>> { 
	jmp	L_yakc_32
L_yakc_33:
	; >>>>> Line:	129
	; >>>>> YKEnterMutex(); 
	mov	ax, word [YKList]
	mov	word [bp-2], ax
	; >>>>> Line:	129
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	130
	; >>>>> while (currentTCB != 0) { 
	jmp	L_yakc_35
L_yakc_34:
	; >>>>> Line:	131
	; >>>>> if (currentTCB->state == RUNNING) { 
	mov	si, word [bp-2]
	add	si, 8
	cmp	word [si], 2
	jne	L_yakc_37
	; >>>>> Line:	132
	; >>>>> break; 
	jmp	L_yakc_36
	jmp	L_yakc_38
L_yakc_37:
	; >>>>> Line:	134
	; >>>>> else if (currentTCB->state == READY) { 
	mov	si, word [bp-2]
	add	si, 8
	cmp	word [si], 1
	jne	L_yakc_39
	; >>>>> Line:	135
	; >>>>> ++YKCtxSwCount; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	136
	; >>>>> YKDispatcher(currentTCB, dispatcher_type); 
	push	word [bp+4]
	push	word [bp-2]
	call	YKDispatcher
	add	sp, 4
	; >>>>> Line:	137
	; >>>>> break; 
	jmp	L_yakc_36
L_yakc_39:
L_yakc_38:
	; >>>>> Line:	139
	; >>>>> currentTCB = currentTCB->next; 
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_35:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_34
L_yakc_36:
	; >>>>> Line:	141
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_32:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_33
L_yakc_41:
	DB	"block dispatch",0xA,0
	ALIGN	2
YKDispatcher:
	; >>>>> Line:	159
	; >>>>> { 
	jmp	L_yakc_42
L_yakc_43:
	; >>>>> Line:	163
	; >>>>> old_task = running_task; 
	mov	word [bp-2], 0
	mov	si, word [bp+4]
	add	si, 20
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	163
	; >>>>> old_task = running_task; 
	mov	ax, word [running_task]
	mov	word [old_task], ax
	; >>>>> Line:	165
	; >>>>> if(FirstTime) { 
	mov	ax, word [FirstTime]
	test	ax, ax
	je	L_yakc_44
	; >>>>> Line:	166
	; >>>>> task->firstTime = 0; 
	mov	si, word [bp+4]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	167
	; >>>>> FirstTime = 0; 
	mov	word [FirstTime], 0
	; >>>>> Line:	169
	; >>>>> running_task = task; 
	mov	ax, word [bp+4]
	mov	word [running_task], ax
	jmp	L_yakc_45
L_yakc_44:
	; >>>>> Line:	172
	; >>>>> else if (running_task->state == BLOCKED) { 
	mov	si, word [running_task]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_46
	; >>>>> Line:	173
	; >>>>> running_task = task; 
	mov	ax, word [bp+4]
	mov	word [running_task], ax
	; >>>>> Line:	174
	; >>>>> if (!(task->firstTime)) { 
	mov	si, word [bp+4]
	add	si, 20
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_47
	; >>>>> Line:	175
	; >>>>> task->firstTime = 0; 
	mov	si, word [bp+4]
	add	si, 20
	mov	word [si], 0
	jmp	L_yakc_48
L_yakc_47:
	; >>>>> Line:	181
	; >>>>> task->firstTime = 0; 
	mov	si, word [bp+4]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	182
	; >>>>> task->state = RUNNING; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 2
L_yakc_48:
	jmp	L_yakc_49
L_yakc_46:
	; >>>>> Line:	188
	; >>>>> task->firstTime = 0; 
	mov	si, word [bp+4]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	190
	; >>>>> old_task->state = READY; 
	mov	si, word [old_task]
	add	si, 8
	mov	word [si], 1
	; >>>>> Line:	191
	; >>>>> task->state = RUNNING; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 2
	; >>>>> Line:	192
	; >>>>> e 
	mov	ax, word [bp+4]
	mov	word [running_task], ax
L_yakc_49:
L_yakc_45:
	; >>>>> Line:	198
	; >>>>> if (dispatcher_type == 2) { 
	cmp	word [bp+6], 2
	jne	L_yakc_50
	; >>>>> Line:	199
	; >>>>> printString("block dispatch\n"); 
	mov	ax, L_yakc_41
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	200
	; >>>>> if(enable){ 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_51
	; >>>>> Line:	201
	; >>>>> YKSecond(); 
	call	YKSecond
	jmp	L_yakc_52
L_yakc_51:
	; >>>>> Line:	204
	; >>>>> YKDispHandler(); 
	call	YKDispHandler
L_yakc_52:
	jmp	L_yakc_53
L_yakc_50:
	; >>>>> Line:	207
	; >>>>> else if (dispatcher_type == 0) { 
	mov	ax, word [bp+6]
	test	ax, ax
	jne	L_yakc_54
	; >>>>> Line:	208
	; >>>>> YKFirst(); 
	call	YKFirst
	jmp	L_yakc_55
L_yakc_54:
	; >>>>> Line:	211
	; >>>>> YKISR(); 
	call	YKISR
L_yakc_55:
L_yakc_53:
	mov	sp, bp
	pop	bp
	ret
L_yakc_42:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_43
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	219
	; >>>>> { 
	jmp	L_yakc_57
L_yakc_58:
	; >>>>> Line:	221
	; >>>>> if (count == 0) return; 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_59
	; >>>>> Line:	221
	; >>>>> if (count == 0) return; 
	jmp	L_yakc_60
L_yakc_59:
	; >>>>> Line:	222
	; >>>>> running_task->delay_counter = count; 
	mov	si, word [running_task]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	223
	; >>>>> running_task->state = BLOCKED; 
	mov	si, word [running_task]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	226
	; >>>>> YKScheduler(2); 
	mov	ax, 2
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_60:
	mov	sp, bp
	pop	bp
	ret
L_yakc_57:
	push	bp
	mov	bp, sp
	jmp	L_yakc_58
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	233
	; >>>>> { 
	jmp	L_yakc_62
L_yakc_63:
	; >>>>> Line:	234
	; >>>>> ++YK_Depth; 
	inc	word [YK_Depth]
	mov	sp, bp
	pop	bp
	ret
L_yakc_62:
	push	bp
	mov	bp, sp
	jmp	L_yakc_63
	ALIGN	2
YKExitISR:
	; >>>>> Line:	239
	; >>>>> { 
	jmp	L_yakc_65
L_yakc_66:
	; >>>>> Line:	240
	; >>>>> --YK_Depth; 
	dec	word [YK_Depth]
	; >>>>> Line:	241
	; >>>>> if (YK_Depth == 0){ 
	mov	ax, word [YK_Depth]
	test	ax, ax
	jne	L_yakc_67
	; >>>>> Line:	242
	; >>>>> depthMoreOne = 0; 
	mov	word [depthMoreOne], 0
	; >>>>> Line:	243
	; >>>>> YKSche 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_67:
	mov	sp, bp
	pop	bp
	ret
L_yakc_65:
	push	bp
	mov	bp, sp
	jmp	L_yakc_66
L_yakc_69:
	DB	"Set to ready",0xA,0
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	250
	; >>>>> { 
	jmp	L_yakc_70
L_yakc_71:
	; >>>>> Line:	252
	; >>>>> ++YKTickNum; 
	mov	ax, word [YKList]
	mov	word [bp-2], ax
	; >>>>> Line:	252
	; >>>>> ++YKTickNum; 
	inc	word [YKTickNum]
	; >>>>> Line:	253
	; >>>>> while (currentTCB != 0) { 
	jmp	L_yakc_73
L_yakc_72:
	; >>>>> Line:	254
	; >>>>> if (currentTCB->task == YKIdleTask) return; 
	mov	si, word [bp-2]
	add	si, 18
	mov	ax, YKIdleTask
	cmp	ax, word [si]
	jne	L_yakc_75
	; >>>>> Line:	254
	; >>>>> if (currentTCB->task == YKIdleTask) return; 
	jmp	L_yakc_76
L_yakc_75:
	; >>>>> Line:	256
	; >>>>> if (currentTCB->delay_counter != 0) { 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_77
	; >>>>> Line:	257
	; >>>>> --(currentTCB->delay_counter); 
	mov	si, word [bp-2]
	add	si, 12
	dec	word [si]
	; >>>>> Line:	258
	; >>>>> if (currentTCB->delay_counter == 0) { 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_78
	; >>>>> Line:	259
	; >>>>> currentTCB->state = READY; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 1
	; >>>>> Line:	260
	; >>>>> printString("Set to ready\n"); 
	mov	ax, L_yakc_69
	push	ax
	call	printString
	add	sp, 2
L_yakc_78:
L_yakc_77:
	; >>>>> Line:	263
	; >>>>> currentTCB = currentTCB->next; 
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_73:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_72
L_yakc_74:
L_yakc_76:
	mov	sp, bp
	pop	bp
	ret
L_yakc_70:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_71
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
YK_Depth:
	TIMES	2 db 0
FirstTime:
	TIMES	2 db 0
tcb_array:
	TIMES	44 db 0
YKList:
	TIMES	2 db 0
running_task:
	TIMES	2 db 0
old_task:
	TIMES	2 db 0
IdleTskStk:
	TIMES	512 db 0
depthMoreOne:
	TIMES	2 db 0
